### ISSUE TITLE
Missing module node-rsa

### ISSUE THREAD

**Issue by steelydev** [spark/softap-setup-js#6]
When doing:

```
browserify softap.js -s SoftAPSetup -o softap-browser.js
```

it fails with:

```
Error: Cannot find module 'node-rsa' from '/Library/WebServer/Documents/wifire/softap-setup-js-master'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by msolters** [comment]
Did you run `npm install` first?  What's your version of node (`node -v`)?

**Comment by steelydev** [comment]
No I didn't.  That seems to have done the trick.  I'm stuck on node v0.10.29 because of the particle CLI being stuck on that version.  Thank you very much!

**Comment by affinity-matrix** [comment]
yay, thanks for your help @msolters!

**Comment by affinity-matrix** [comment]
@steelydev you can use 0.12.x with the Particle CLI!
